apiVersion: v1
kind: Service
metadata:
  name: http-server
  namespace: cicd
spec:
  selector:
    app: http-server
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30001